/* tslint:disable */
// generated by typescript-json-validator
import { inspect } from "util";
import Ajv = require("ajv");
import GameData from "./GameData";
export const ajv = new Ajv({
  allErrors: true,
  coerceTypes: false,
  format: "fast",
  nullable: true,
  unicode: true,
  uniqueItems: true,
  useDefaults: true,
});

ajv.addMetaSchema(require("ajv/lib/refs/json-schema-draft-06.json"));

export { GameData };
export const GameDataSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  defaultProperties: [],
  properties: {
    faceDirection: {
      defaultProperties: [],
      properties: {
        x: {
          type: "number",
        },
        y: {
          type: "number",
        },
        z: {
          type: "number",
        },
      },
      required: ["x", "y", "z"],
      type: "object",
    },
    gameClientID: {
      type: "string",
    },
    gameUserID: {
      type: "string",
    },
    position: {
      defaultProperties: [],
      properties: {
        x: {
          type: "number",
        },
        y: {
          type: "number",
        },
        z: {
          type: "number",
        },
      },
      required: ["x", "y", "z"],
      type: "object",
    },
    upDirection: {
      defaultProperties: [],
      properties: {
        x: {
          type: "number",
        },
        y: {
          type: "number",
        },
        z: {
          type: "number",
        },
      },
      required: ["x", "y", "z"],
      type: "object",
    },
  },
  required: [
    "faceDirection",
    "gameClientID",
    "gameUserID",
    "position",
    "upDirection",
  ],
  type: "object",
};
export type ValidateFunction<T> = ((data: unknown) => data is T) &
  Pick<Ajv.ValidateFunction, "errors">;
export const isGameData = ajv.compile(GameDataSchema) as ValidateFunction<
  GameData
>;
export default function validate(value: unknown): GameData {
  if (isGameData(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(
        isGameData.errors!.filter((e: any) => e.keyword !== "if"),
        { dataVar: "GameData" }
      ) +
        "\n\n" +
        inspect(value)
    );
  }
}
